//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ___go_build_k8s_io_gengo_examples_deepcopy_gen. DO NOT EDIT.

package common

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIDReq) DeepCopyInto(out *AccountIDReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIDReq.
func (in *AccountIDReq) DeepCopy() *AccountIDReq {
	if in == nil {
		return nil
	}
	out := new(AccountIDReq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIDRes) DeepCopyInto(out *AccountIDRes) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIDRes.
func (in *AccountIDRes) DeepCopy() *AccountIDRes {
	if in == nil {
		return nil
	}
	out := new(AccountIDRes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIDSlice) DeepCopyInto(out *AccountIDSlice) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.AccountIds != nil {
		in, out := &in.AccountIds, &out.AccountIds
		*out = make([]uint64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIDSlice.
func (in *AccountIDSlice) DeepCopy() *AccountIDSlice {
	if in == nil {
		return nil
	}
	out := new(AccountIDSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountMatchInfo) DeepCopyInto(out *AccountMatchInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountMatchInfo.
func (in *AccountMatchInfo) DeepCopy() *AccountMatchInfo {
	if in == nil {
		return nil
	}
	out := new(AccountMatchInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountRegionSlice) DeepCopyInto(out *AccountRegionSlice) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountRegionSlice.
func (in *AccountRegionSlice) DeepCopy() *AccountRegionSlice {
	if in == nil {
		return nil
	}
	out := new(AccountRegionSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasInterfaceMap) DeepCopyInto(out *AliasInterfaceMap) {
	{
		in := &in
		*out = make(AliasInterfaceMap, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = val.DeepCopyAliasInterface()
			}
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasInterfaceMap.
func (in AliasInterfaceMap) DeepCopy() AliasInterfaceMap {
	if in == nil {
		return nil
	}
	out := new(AliasInterfaceMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AliasInterfaceSlice) DeepCopyInto(out *AliasInterfaceSlice) {
	{
		in := &in
		*out = make(AliasInterfaceSlice, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = (*in)[i].DeepCopyAliasInterface()
			}
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliasInterfaceSlice.
func (in AliasInterfaceSlice) DeepCopy() AliasInterfaceSlice {
	if in == nil {
		return nil
	}
	out := new(AliasInterfaceSlice)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAccount) DeepCopyInto(out *EAccount) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAccount.
func (in *EAccount) DeepCopy() *EAccount {
	if in == nil {
		return nil
	}
	out := new(EAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECreatePlayer) DeepCopyInto(out *ECreatePlayer) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECreatePlayer.
func (in *ECreatePlayer) DeepCopy() *ECreatePlayer {
	if in == nil {
		return nil
	}
	out := new(ECreatePlayer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGameServer) DeepCopyInto(out *EGameServer) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGameServer.
func (in *EGameServer) DeepCopy() *EGameServer {
	if in == nil {
		return nil
	}
	out := new(EGameServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EGameServerManager) DeepCopyInto(out *EGameServerManager) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EGameServerManager.
func (in *EGameServerManager) DeepCopy() *EGameServerManager {
	if in == nil {
		return nil
	}
	out := new(EGameServerManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EMatch) DeepCopyInto(out *EMatch) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EMatch.
func (in *EMatch) DeepCopy() *EMatch {
	if in == nil {
		return nil
	}
	out := new(EMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EProtocol) DeepCopyInto(out *EProtocol) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EProtocol.
func (in *EProtocol) DeepCopy() *EProtocol {
	if in == nil {
		return nil
	}
	out := new(EProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Empty) DeepCopyInto(out *Empty) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Empty.
func (in *Empty) DeepCopy() *Empty {
	if in == nil {
		return nil
	}
	out := new(Empty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIDSlice) DeepCopyInto(out *ExternalIDSlice) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ExternalIds != nil {
		in, out := &in.ExternalIds, &out.ExternalIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIDSlice.
func (in *ExternalIDSlice) DeepCopy() *ExternalIDSlice {
	if in == nil {
		return nil
	}
	out := new(ExternalIDSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindGameServerExtraInfo) DeepCopyInto(out *FindGameServerExtraInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindGameServerExtraInfo.
func (in *FindGameServerExtraInfo) DeepCopy() *FindGameServerExtraInfo {
	if in == nil {
		return nil
	}
	out := new(FindGameServerExtraInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSPlayerPrepareInfo) DeepCopyInto(out *GSPlayerPrepareInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSPlayerPrepareInfo.
func (in *GSPlayerPrepareInfo) DeepCopy() *GSPlayerPrepareInfo {
	if in == nil {
		return nil
	}
	out := new(GSPlayerPrepareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GSPrepareInfo) DeepCopyInto(out *GSPrepareInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.GsPlayerPrepareInfos != nil {
		in, out := &in.GsPlayerPrepareInfos, &out.GsPlayerPrepareInfos
		*out = make([]*GSPlayerPrepareInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GSPlayerPrepareInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GSPrepareInfo.
func (in *GSPrepareInfo) DeepCopy() *GSPrepareInfo {
	if in == nil {
		return nil
	}
	out := new(GSPrepareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gameserver2ServicePkg) DeepCopyInto(out *Gameserver2ServicePkg) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gameserver2ServicePkg.
func (in *Gameserver2ServicePkg) DeepCopy() *Gameserver2ServicePkg {
	if in == nil {
		return nil
	}
	out := new(Gameserver2ServicePkg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchClientInfo) DeepCopyInto(out *MatchClientInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.FileException != nil {
		in, out := &in.FileException, &out.FileException
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.LibResult != nil {
		in, out := &in.LibResult, &out.LibResult
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.NativeResult != nil {
		in, out := &in.NativeResult, &out.NativeResult
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchClientInfo.
func (in *MatchClientInfo) DeepCopy() *MatchClientInfo {
	if in == nil {
		return nil
	}
	out := new(MatchClientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchIDReq) DeepCopyInto(out *MatchIDReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchIDReq.
func (in *MatchIDReq) DeepCopy() *MatchIDReq {
	if in == nil {
		return nil
	}
	out := new(MatchIDReq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchPregameInfo) DeepCopyInto(out *MatchPregameInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchPregameInfo.
func (in *MatchPregameInfo) DeepCopy() *MatchPregameInfo {
	if in == nil {
		return nil
	}
	out := new(MatchPregameInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchPrepareInfo) DeepCopyInto(out *MatchPrepareInfo) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchPrepareInfo.
func (in *MatchPrepareInfo) DeepCopy() *MatchPrepareInfo {
	if in == nil {
		return nil
	}
	out := new(MatchPrepareInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageNotify) DeepCopyInto(out *MessageNotify) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageNotify.
func (in *MessageNotify) DeepCopy() *MessageNotify {
	if in == nil {
		return nil
	}
	out := new(MessageNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageNotifySlice) DeepCopyInto(out *MessageNotifySlice) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Msgs != nil {
		in, out := &in.Msgs, &out.Msgs
		*out = make([]*MessageNotify, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MessageNotify)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageNotifySlice.
func (in *MessageNotifySlice) DeepCopy() *MessageNotifySlice {
	if in == nil {
		return nil
	}
	out := new(MessageNotifySlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NicknameReq) DeepCopyInto(out *NicknameReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NicknameReq.
func (in *NicknameReq) DeepCopy() *NicknameReq {
	if in == nil {
		return nil
	}
	out := new(NicknameReq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDReq) DeepCopyInto(out *OpenIDReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDReq.
func (in *OpenIDReq) DeepCopy() *OpenIDReq {
	if in == nil {
		return nil
	}
	out := new(OpenIDReq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformRegisterReq) DeepCopyInto(out *PlatformRegisterReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformRegisterReq.
func (in *PlatformRegisterReq) DeepCopy() *PlatformRegisterReq {
	if in == nil {
		return nil
	}
	out := new(PlatformRegisterReq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformRegisterRes) DeepCopyInto(out *PlatformRegisterRes) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformRegisterRes.
func (in *PlatformRegisterRes) DeepCopy() *PlatformRegisterRes {
	if in == nil {
		return nil
	}
	out := new(PlatformRegisterRes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayerLogoutReq) DeepCopyInto(out *PlayerLogoutReq) {
	*out = *in
	in.state.DeepCopyInto(&out.state)
	if in.unknownFields != nil {
		in, out := &in.unknownFields, &out.unknownFields
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayerLogoutReq.
func (in *PlayerLogoutReq) DeepCopy() *PlayerLogoutReq {
	if in == nil {
		return nil
	}
	out := new(PlayerLogoutReq)
	in.DeepCopyInto(out)
	return out
}
